### ISSUE TITLE
Consider mentioning in the README.md that this plugin will also apply to `min-height` and `max-height`

### ISSUE THREAD

**Issue by dallanlee** [Faisal-Manzer/postcss-viewport-height-correction#11]
As the issue title explains, I wasn't able to find out if this plugin would apply the same `calc()` solution to `min-height` and `max-height` properties. After searching the repo, I was able to find a test for `max-height`. But I still needed to know about `min-height`. So I tested it myself and confirmed that it does apply. I think it would be helpful to mention this in the readme so that other users can potentially save time and effort. Thanks for the great plugin.

**Comment by Faisal-Manzer** [comment]
Thanks for the issue. Added an example to README for min and max height.

But I think it was clear that the plugin will be applied to any property with `vh` or `vw` as units.
