### ISSUE TITLE
Put changelog to CHANGELOG.md

### ISSUE THREAD

**Issue by ai** [Faisal-Manzer/postcss-viewport-height-correction#2]
Awesome plugin. But you forget to put content to `CHANGELOG.md`.

It is very important for your users to find will it be safe for them to update the plugin’s versions.

Here are other reasons why we put `CHANGELOG.md` to PostCSS plugin template https://keepachangelog.com/en/1.0.0/

**Comment by Faisal-Manzer** [comment]
Added CHANGELOG. Thanks, for your concern.
