### ISSUE TITLE
Consider using document.documentElement.clientHeight in the docs instead of window.innerHeight

### ISSUE THREAD

**Issue by fiznool** [Faisal-Manzer/postcss-viewport-height-correction#3]
`window.innerHeight` is supposed to return the height of the 'layout viewport' (i.e. the height of the browser window as it is laid out) instead of the 'visual viewport' (i.e. the viewport as it is shown to the user). These two viewports are different if the user has zoomed in via pinch-to-zoom.

Sadly iOS appears to report the visual viewport instead of the layout viewport for `window.innerHeight`. It _also_ fires the resize event when the user zooms, meaning a resize event handler that measures `window.innerHeight` can provide peculiar results. In my case, I was using this module to anchor a button to the bottom of screen, and when zooming in, the button would float to the bottom of the visual viewport.

To solve, I used `document.documentElement.clientHeight` to measure the viewport height. On iOS this appears to always return the layout viewport, not the visual viewport.

Although the CSS-Tricks article suggests to use `window.innerHeight`, I don't think it is fit for purpose here, and would suggest `document.documentElement.clientHeight` as a better alternative for the docs in the README.

**Comment by Faisal-Manzer** [comment]
Thanks for notifying this. Zooming in `window.innerHeight` is weird.

**Comment by oustn** [comment]
In iOS 15.5 when the Safari address bar auto hide with scroll, the resize event will be trigger and the `document.documentElement.clientHeight` always not change.
