### ISSUE TITLE
You didn't need to publish a 2.0.0, a 1.1.0 would have been sufficient

### ISSUE THREAD

**Issue by fiznool** [Faisal-Manzer/postcss-viewport-height-correction#9]
I don't believe there were any breaking changes between 1.0.4 -> 2.0.0 - from reading the commit logs, a backwards-compatible change was made to optionally set a different name for the custom variable (instead of `--vh`).

As per semver, this is an 'additive' change that is non-breaking, so a minor version bump would have been sufficient to 1.1.0. The only reason I bring this up is because most people who depend on this package will have an entry such as 

```
"postcss-viewport-height-correction": "^1.0.4"
```

in their `package.json`. The caret `^` means that version `2.0.0` will not automatically be installed, instead the developer must explicitly update their `package.json` file after reading through the changelog.

Perhaps I'm wrong, was this a breaking change? Regardless, I think a note in the changelog would help to clarify.

Thanks again for a really useful module! 😄

**Comment by Faisal-Manzer** [comment]
I will take care for this next time. I will publish `1.1.0` as recommended. Thank you for pointing this out.

**Comment by Faisal-Manzer** [comment]
I published v1.1.0 and will publish updates with semantic versioning.
